### ISSUE TITLE
隐藏加载时的文本视图

### ISSUE THREAD

**Issue by qinxs** [md-reader/md-reader#54]
## 测试实现

```css
body {
  opacity: 0;  /* 或者其他方式 */
}
body.loaded {
  opacity: 1;
}
```
1 `content.css` 增加上述css

2 等md文档渲染完成 给 body 添加 `loaded`样式

3 manifest.json 的`content_scripts`注入改为 `"RunAt": "document_start"`

## 文本视图截图

![加载过程的文本视图](https://github.com/md-reader/md-reader/assets/13647698/aa19b141-b75b-4f0f-af99-ee46db61af56)
