### ISSUE TITLE
自定义css可以出一个说明文档吗？

### ISSUE THREAD

**Issue by wumingsheng** [md-reader/md-reader#68]
期待以及的自定义css功能终于出来了，感谢。自定义css可以给一个使用文档吗？例如，哪些样式可以自定义？名字是什么等

**Comment by Heroor** [comment]
文档的话暂时还没有计划，其实如果比较熟悉 CSS 就足以修改大部分样式了，我可以简单说明一下思路：

- 如果想修改文章内容区域，可以参考 https://github.com/md-reader/theme/blob/main/src/theme.less 文件，CSS 的选择器最好命中 `article`，例如修改 h1 元素的字体颜色：
```css
article h1 {
  color: red;
}
```

- 如果想修改功能界面的样式，可以尝试打开 浏览器控制台 获取对应元素的类名，直接添加对应的样式即可，例如修改侧边栏背景色：
```css
aside.mdr-side {
  background: #f5f5f5;
}
```
不过功能界面元素的类名在未来的版本中可能发生变动，版本升级后自行调整即可。也请谨慎修改功能界面区域的样式，以免影响使用
