### ISSUE TITLE
竖屏支持

### ISSUE THREAD

**Issue by bennyyip** [md-reader/md-reader#70]
在竖屏里，每行的文字显示不全。
浏览器是 Firefox/136.0
![Image](https://github.com/user-attachments/assets/db304b93-43f1-4908-82d5-598abbdccc79)

**Comment by bennyyip** [comment]
不是插件的问题，是因为Firefox的窗口的min-width比我的屏幕窄了，导致显示不全。在 userChrome.css 改小就没事了。
```css
/* Reduce minimum window width for Fx74 */
:root:not([chromehidden~="toolbar"]){
  /* Fx74 default is 450px on Windows */
  min-width: 250px !important;
}
```
